server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

database:
  driverClass: org.h2.Driver
  url: jdbc:h2:mem:ghostprotocol;DB_CLOSE_DELAY=-1

messaging:
  domain: ghostprotocol-api-dev.ngrok-free.app

admin:
  email: admin@ghostprotocol.org
  password: admin123

storage:
  local:
    baseDir: /tmp/ghostprotocol-storage
    attachmentsDir: /tmp/ghostprotocol-storage/attachments
    profilesDir: /tmp/ghostprotocol-storage/profiles
    vaultDir: /tmp/ghostprotocol-storage/vault
