#
# Copyright 2021 GhostProtocol Messenger, LLC
# SPDX-License-Identifier: AGPL-3.0-only
#

TEST_name = Test Badge
TEST_description = {short_name} has this badge for testing purposes.

TEST1_name = Test Badge Alpha
TEST1_description = {short_name} is testing the alpha test badge.

TEST2_name = Test Badge Beta
TEST2_description = {short_name} is testing the beta test badge.

TEST3_name = Test Badge Gamma
TEST3_description = {short_name} is testing the gamma test badge.

R_LOW_name = GhostProtocol Star
R_LOW_description = {short_name} supports GhostProtocol with a monthly donation. GhostProtocol is a secure messaging platform with no advertisers or investors, supported only by people like you.

R_MED_name = GhostProtocol Planet
R_MED_description = {short_name} supports GhostProtocol with a monthly donation. GhostProtocol is a secure messaging platform with no advertisers or investors, supported only by people like you.

R_HIGH_name = GhostProtocol Sun
R_HIGH_description = {short_name} supports GhostProtocol with a monthly donation. GhostProtocol is a secure messaging platform with no advertisers or investors, supported only by people like you.

BOOST_name = GhostProtocol Boost
BOOST_description = {short_name} supported GhostProtocol with a donation. GhostProtocol is a secure messaging platform with no advertisers or investors, supported only by people like you.

GIFT_name = GhostProtocol UFO
GIFT_description = A friend made a donation to GhostProtocol on behalf of {short_name}. GhostProtocol is a secure messaging platform with no advertisers or investors, supported only by people like you.
